version: 1
disable_existing_loggers: false

formatters:
  standard:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'
  
  detailed:
    format: '%(asctime)s - %(name)s - %(levelname)s - %(module)s - %(funcName)s:%(lineno)d - %(message)s'
    datefmt: '%Y-%m-%d %H:%M:%S'

  simple:
    format: '%(levelname)s - %(message)s'

handlers:
  console:
    class: logging.StreamHandler
    level: DEBUG
    formatter: standard
    stream: ext://sys.stdout

  file:
    class: logging.handlers.RotatingFileHandler
    level: DEBUG
    formatter: detailed
    filename: ${LOG_FILE:-teachingtools.log}
    mode: a
    maxBytes: ${LOG_MAX_BYTES:-10485760}
    backupCount: ${LOG_BACKUP_COUNT:-5}
    encoding: utf-8

  error_file:
    class: logging.handlers.RotatingFileHandler
    level: ERROR
    formatter: detailed
    filename: ${ERROR_LOG_FILE:-teachingtools_errors.log}
    mode: a
    maxBytes: ${ERROR_LOG_MAX_BYTES:-10485760}
    backupCount: ${ERROR_LOG_BACKUP_COUNT:-5}
    encoding: utf-8

loggers:
  grading_web_ui:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  grading_web_ui.web_api.services.manual_alignment:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  grading_web_ui.web_api.services.problem_service:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  GradingWebUI:
    level: DEBUG
    handlers: [console, file]
    propagate: false

  lms_interface:
    level: INFO
    handlers: [console, file]
    propagate: false
    
  canvasapi:
    level: WARNING
    handlers: [console]
    propagate: false

root:
  level: INFO
  handlers: [console, file, error_file]
