(() => {
  const sessionsElement = document.querySelector('#sessions');
  const bucketsElement = document.querySelector('#buckets');
  const resultsPanel = document.querySelector('#results-panel');
  const resultsElement = document.querySelector('#results');
  let sessions = [];
  let buckets = [
    {name: 'Long response (6 & 8 points)', points: '6, 8'},
    {name: 'Medium response (4 points)', points: '4'},
    {name: 'Short response (1 & 2 points)', points: '1, 2'},
  ];
  const escapeHtml = value => String(value ?? '').replace(/[&<>'"]/g, character => ({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'})[character]);
  async function api(url, options) { const response = await fetch(url, options); const body = await response.json().catch(() => ({})); if (!response.ok) throw new Error(body.detail || 'Request failed'); return body; }
  function sessionName(session) { return session.session_name || session.assignment_name || `Session ${session.id}`; }
  function renderSessions() { sessionsElement.innerHTML = sessions.map(session => `<label class="session-option"><input type="checkbox" value="${session.id}"><span>${escapeHtml(sessionName(session))} <small>(Session ${session.id})</small></span></label>`).join('') || 'No sessions available.'; }
  function renderBuckets() { bucketsElement.innerHTML = buckets.map((bucket, index) => `<div class="bucket"><input data-field="name" data-index="${index}" value="${escapeHtml(bucket.name)}" aria-label="Bucket name"><input data-field="points" data-index="${index}" value="${escapeHtml(bucket.points)}" aria-label="Point values"><button class="danger" data-remove="${index}" type="button">Remove</button></div>`).join(''); bucketsElement.querySelectorAll('input').forEach(input => input.addEventListener('input', () => { buckets[Number(input.dataset.index)][input.dataset.field] = input.value; })); bucketsElement.querySelectorAll('[data-remove]').forEach(button => button.addEventListener('click', () => { buckets.splice(Number(button.dataset.remove), 1); renderBuckets(); })); }
  function fmt(value) { return value === null || value === undefined ? '—' : `${(value * 100).toFixed(1)}%`; }
  function renderResults(rows) { resultsPanel.hidden = false; resultsElement.innerHTML = `<table><thead><tr><th>Session</th><th>Bucket / questions</th><th>Responses scored</th><th>Normalized score</th><th>Blank</th><th>Normalized-score distribution</th></tr></thead><tbody>${rows.map(row => `<tr><td>${escapeHtml(row.session.name)}<br><small>Session ${row.session.id}</small></td><td>${escapeHtml(row.bucket)}<br><small>${row.point_values.join(', ')} points · Q${row.question_numbers.join(', Q') || '—'}</small></td><td class="metric">${row.response_count} total<br>${row.scored_count} scored</td><td class="metric">${fmt(row.mean_normalized)} mean<br>± ${fmt(row.stddev_normalized)} stddev</td><td class="metric">${row.blank_percentage === null ? '—' : `${row.blank_percentage.toFixed(1)}%`}<br><small>${row.blank_count}/${row.response_count}</small></td><td><div class="hist" title="${row.distribution.map(bin => `${bin.label}: ${bin.count}`).join(', ')}">${row.distribution.map(bin => `<span style="width:${bin.percentage}%"></span>`).join('')}</div><small>${row.distribution.map(bin => `${bin.label}: ${bin.percentage.toFixed(0)}%`).join(' · ')}</small></td></tr>`).join('')}</tbody></table>`; }
  document.querySelector('#add-bucket').addEventListener('click', () => { buckets.push({name: 'New bucket', points: ''}); renderBuckets(); });
  document.querySelector('#compare').addEventListener('click', async () => { const session_ids = [...sessionsElement.querySelectorAll('input:checked')].map(input => Number(input.value)); const normalizedBuckets = buckets.map(bucket => ({name: bucket.name.trim(), points: bucket.points.split(',').map(value => Number(value.trim())).filter(value => Number.isFinite(value))})).filter(bucket => bucket.name && bucket.points.length); if (!session_ids.length) return alert('Select at least one session.'); if (!normalizedBuckets.length) return alert('Define at least one bucket with point values.'); try { const data = await api('/api/session-comparison', {method:'POST', headers:{'Content-Type':'application/json'}, body:JSON.stringify({session_ids, buckets: normalizedBuckets})}); renderResults(data.rows); } catch (error) { alert(error.message); } });
  Promise.all([api('/api/sessions')]).then(([loaded]) => { sessions = loaded; renderSessions(); renderBuckets(); }).catch(error => { sessionsElement.textContent = error.message; });
})();
